[project]
name = "helio"
dynamic = ["version"]
description = "Capture video streams"
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "cmd2>=2.5.11",
    "curl-cffi>=0.11.0b1",
    "m3u8>=6.0.0",
    "pydantic-settings>=2.8.1",
    "pygithub>=2.6.1",
    "python-dotenv>=1.1.0",
    "rnet>=2.2.1",
    "tabulate>=0.9.0",
]

[project.urls]
repository = "https://github.com/beyChill/helio"


[project.scripts]
start = "stardust.start:main"
