[project]
name = "helio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "cmd2>=2.5.11",
    "curl-cffi>=0.10.0",
    "m3u8>=6.0.0",
    "pydantic-settings>=2.8.1",
    "pygithub>=2.6.1",
    "python-dotenv>=1.1.0",
    "rnet>=2.2.1",
]
